#+TITLE: Bugs in Anova Test?
#+AUTHOR: Tong, Xiaoran

Suppose we have the truth modeled by
\begin{align}
	\boldsymbol{y} = \boldsymbol{Aa} + \boldsymbol{Bb} + \boldsymbol{r}, \quad
	\boldsymbol{r} \sim \mathcal{N}\left(\boldsymbol{0}, \mbox{Var}(\boldsymbol{r})\boldsymbol{I} \right),
\end{align}
where $\{\boldsymbol{y}, \boldsymbol{A}, \boldsymbol{B}\}$ are observed primary data.

* Primary Regression
Fit a full model, we have
\begin{align}
	\boldsymbol{r} = \boldsymbol{y} - \boldsymbol{Aa} - \boldsymbol{Bb}. \quad
\end{align}
The likelihood of the privary data is
\begin{align}
	-\frac{1}{2}\boldsymbol{r}'\boldsymbol{r} / \mbox{Var}(\boldsymbol{r})
	-\frac{1}{2}\mbox{Var}(\boldsymbol{r}) - \mbox{C}
\end{align}

Fit a reduced model with $\boldsymbol{A}$ only, we have
\begin{align}
	\boldsymbol{s} = \boldsymbol{y} - \boldsymbol{Ac}, \quad
\end{align}
and the likelihood becomes
\begin{align}
	-\frac{1}{2}\boldsymbol{s}'\boldsymbol{s} / \mbox{Var}(\boldsymbol{s})
	-\frac{1}{2}\mbox{Var}(\boldsymbol{s}) - \mbox{C}
\end{align}

* Secondary Regression
We treat $\boldsymbol{s}$ -- residual of the reduce model as a response.

Fit a full model with both A and B again, that is, s = A + B + t
\begin{align}
	\boldsymbol{t} = \boldsymbol{s} - \boldsymbol{Ad} - \boldsymbol{Be}
		       = \boldsymbol{y} - \boldsymbol{Ac} 
		       - \boldsymbol{Ad} - \boldsymbol{Be},
\end{align}
where only $\boldsymbol{d}$ and $\boldsymbol{e}$ are flexible, it turns out
\begin{align}
	\boldsymbol{t} = \boldsymbol{r}, \quad
	\boldsymbol{c} + \boldsymbol{d} = \boldsymbol{a},
\end{align}
and the  likelihood of secondary  data $\{\boldsymbol{s,  A, B}\}$ is  the same
with the primary data under the full model, which is
\begin{align*}
	-\frac{1}{2}\boldsymbol{r}'\boldsymbol{r} / \mbox{Var}(\boldsymbol{r})
	-\frac{1}{2}\mbox{Var}(\boldsymbol{r}) - \mbox{C}
\end{align*}

Fit a reduced mode with only A
\begin{align}
	\boldsymbol{u} = \boldsymbol{s} - \boldsymbol{Af}
		       = \boldsymbol{y} - \boldsymbol{Ac} - \boldsymbol{Af},
\end{align}
where only $\boldsymbol{f}$ is flexible, turns out
\begin{align}
	\boldsymbol{u} = \boldsymbol{s}, \quad
	\boldsymbol{f} = \boldsymbol{0}
\end{align}
and the likelihood is the same with the primary data under the reduced model
\begin{align*}
	-\frac{1}{2}\boldsymbol{s}'\boldsymbol{s} / \mbox{Var}(\boldsymbol{s})
	-\frac{1}{2}\mbox{Var}(\boldsymbol{s}) - \mbox{C}
\end{align*}

* Result
Consequently, the likelihood ratio test of  the full model versus reduced model
under primary data and secondary data are the same.
